const ON_FETCH_SONG_FROM_SERVER = 'ON_FETCH_SONG_FROM_SERVER'
const ON_RE_FETCH_DATA = 'ON_RE_FETCH_DATA'
const ON_SAVE_QUERY = 'ON_SAVE_QUERY'

export {
    ON_FETCH_SONG_FROM_SERVER,
    ON_RE_FETCH_DATA,
    ON_SAVE_QUERY
}